#!/bin/bash
set -e

function echoErrorMessage () {
  echo << EOM
Warning, you have uncommitted changes!
Perhaps you forgot to `git add` after linter?
If you're working on multiple changes at a time, you can:
  - `git stash push /path/to/file` to stash just some changes
  - make a separate branch with some of your changes only.
EOM
}

[ ! -z "$(git diff)" ] && echoErrorMessage && exit 1;

npm run lint 
npm run test