#!/bin/bash


if git status --porcelain=v1 | grep MM ; then
  cat << EOM

Warning, you have double-modified uncommitted changes (above)!
Perhaps you forgot to "git add" after linter?

If you're working on multiple changes at a time, you can:
  - "git stash push /path/to/file" to stash just some changes
  - make a separate branch with some of your changes only.
EOM
  exit 1
fi


if ! (git status --porcelain=v1 | cut -c 1 | grep -e "[DAM]" > /dev/null) ; then
  echo "No changes to commit, abort."
  exit 1
fi

set -e
npm run lint
npm run test
