version: '2'

services:
  workflowish:
    build: .
    ports:
      - 5173:5173 # frontend
      - 5174:5174 # backend
    volumes: # for persistence
      - data:/home/workflowish/backend-src/filedb